-- 1. Tabla de Configuración (Singleton: Solo permitimos una fila con ID=1)
create table public.config (
  id int primary key default 1,
  market_price numeric default 0.63,
  adena_rate numeric default 30000,
  initial_capital numeric default 0,
  template_unified text,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  constraint single_row check (id = 1)
);

-- Inicializar configuración por defecto
insert into public.config (id, market_price, adena_rate, initial_capital)
values (1, 0.63, 30000, 0)
on conflict (id) do nothing;

-- 2. Tabla de Socios
create table public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  coins_invested int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Tabla de Inventario (Assets)
create table public.assets (
  id bigint generated by default as identity primary key,
  name text not null,
  stock int default 0,
  usdt_value numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Tabla de Ventas
create table public.sales (
  id bigint generated by default as identity primary key,
  date timestamp with time zone default timezone('utc'::text, now()),
  type text not null, -- 'individual', 'global', 'item_sale'
  partner_id bigint references public.partners(id),
  item_id bigint references public.assets(id),
  partner_name text, -- Snapshot del nombre (por si se borra el socio)
  item_name text,    -- Snapshot del nombre del item
  amount int not null,
  price numeric not null,
  profit numeric not null,
  confirmed boolean default false,
  distribution jsonb, -- JSON para guardar el desglose de ventas globales
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar Row Level Security (RLS) - Recomendado por seguridad
alter table public.config enable row level security;
alter table public.partners enable row level security;
alter table public.assets enable row level security;
alter table public.sales enable row level security;

-- Políticas de acceso (Abiertas para desarrollo, restringir en producción)
create policy "Public Access Config" on public.config for all using (true);
create policy "Public Access Partners" on public.partners for all using (true);
create policy "Public Access Assets" on public.assets for all using (true);
create policy "Public Access Sales" on public.sales for all using (true);

-- 5. Tabla de Paquetes
create table public.packages (
  id bigint generated by default as identity primary key,
  amount int not null unique, -- Cantidad en 'k' (ej. 10, 15)
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar RLS para paquetes
alter table public.packages enable row level security;
create policy "Public Access Packages" on public.packages for all using (true);

-- Insertar paquetes por defecto
insert into public.packages (amount) values 
  (10), (15), (20), (30), (50)
on conflict (amount) do nothing;